# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use
# For example: application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

logging:
  file:
    path: /opt/logs/config-server
  level:
    root: info
    vn.ptit.configserver: info
  charset:
    console: UTF-8
    file: UTF-8

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thoaidc/movie-booking-app.git
          search-paths:
            - file:./configs
            - file:./configs/{application}
          default-label: main
          clone-on-start: true
          timeout: 10
        encrypt:
          enabled: true
