# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use
# For example: application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

logging:
  file:
    path: opt/logs/config-server
  level:
    root: debug
    org.springframework.cloud.config: debug
    org.springframework.vault: debug
    org.eclipse.jgit.util: info
    org.eclipse.jgit.transport: info
    org.eclipse.jgit.internal.storage.file: info
  charset:
    console: UTF-8
    file: UTF-8

spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./configs
            - file:./configs/{application}
